// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzepmywtihvjgewdrynx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6ZXBteXd0aWh2amdld2RyeW54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxODE3NTcsImV4cCI6MjA5MDc1Nzc1N30.zAZuysB3bKvlPPdVnpY659_AakjUUWhzO6B8MXZGILA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});